### ISSUE TITLE
v0.1.0: tag and release this version

### ISSUE THREAD

**Issue by philips** [opencontainers/image-spec#66]
I think we should tag and release v0.1.0 of the image spec. We have imported the relevant docs, added information about the media types, and created the new media types for the OCI. It isn't perfect but I want to start having discussions with people implementing registries and build systems and I think it is in good enough shape to start having those discussions.

Any objections @opencontainers/image-spec-maintainers ?

Major themes for the v0.2.0 spec

- [ ] Finish discussion on naming (#11) and add a solution to the spec 
- [ ] Improve spec based on feedback from teams implementing registries/build systems
- [ ] Introduce the oci-image-tool #43 
- [ ] Cleanup the serialization spec #36 
- [ ] Improved introductory text

See the [full milestone for v0.2.0 ](https://github.com/opencontainers/image-spec/milestones/v0.2.0). If you can take up one of these issues please do! I want to get the v0.2.0 release out in about 2-3 weeks.

**Comment by philips** [comment]
Here are the major themes accomplished in v0.1.0: https://github.com/opencontainers/image-spec/issues?q=milestone%3Av0.1.0+is%3Aclosed

**Comment by vbatts** [comment]
Should we include a ChangeLog for v0.1.0 release? otherwise I can push it out right now.

**Comment by caniszczyk** [comment]
is there a release process defined yet where a certain number of maintainers need to +1 / LGTM? would be nice to get input from more of the @opencontainers/image-spec-maintainers before doing a v0.1.0

**Comment by philips** [comment]
@caniszczyk On the image spec we just try and get a few of the MAINTAINERS saying it LGTM and it seems to work fine. We have the technical process but it isn't very in-depth: https://github.com/opencontainers/image-spec/blob/a096dacf27d0677e295244c8c7e350d818b04b22/project.md#project-docs

**Comment by philips** [comment]
@vbatts a ChangeLog isn't likely super helpful as this is an initial release. v0.2.0 should have a ChangeLog though!

**Comment by stevvooe** [comment]
@philips Does tagging this version imply anything about compatibility? For example, does 0.2.0 need to be compatible with 0.1.0?

My concern is that people will start implementing, expecting stability but these point releases should really be considered alpha.

**Comment by wking** [comment]
On Thu, May 05, 2016 at 12:28:14PM -0700, Stephen Day wrote:
> For example, does 0.2.0 need to be compatible with 0.1.0?

Not in SemVer.  From §4 [1]:

  Major version zero (0.y.z) is for initial development. Anything may
  change at any time. The public API should not be considered stable.

[1]: http://semver.org/spec/v2.0.0.html

**Comment by philips** [comment]
@stevvooe What @wking is correct. There is no intention of maintaining compatibility but to 1) get in the habit of doing releases 2) start the discussion with people about implementing stuff and get feedback on the spec.

**Comment by philips** [comment]
@stevvooe Can I take your 👍 on my comment as a +1 on doing a release?

**Comment by stevvooe** [comment]
@philips That is a 👍 of understanding. I'm a little reticent to tag a release at this point but I don't have a good reason not to.

We may want to adjust the road map for 0.2.0. The focus there needs to be on getting a solid distributable format, along with conversion to and from a runc bundle. Maybe move those items off of this description to a milestone or epic?

**Comment by philips** [comment]
Alright, I haven't heard any objections. We are going to go ahead and tag the release today.

@vbatts still have bandwidth to tag and release?

**Comment by brendandburns** [comment]
+1 to tagging a release.  I think getting into a regular habit (monthly? bi-weekly?) will oil the release machinery in a good way.

@vbatts if you don't have bandwidth, I can do it...

**Comment by philips** [comment]
@brendandburns Please try and get the release out if you have time. I believe @vbatts is on a ✈️ today.

+1 on doing monthly or bi-weekly releases. The original roadmap had monthly releases and we are behind, eek!

**Comment by vbatts** [comment]
I'll do it post-haste

**Comment by vbatts** [comment]
Oh bugger. The nice dot diagram doesn't jive with pandoc for the pdf.
```
pandoc: Could not find image `media-types.png', skipping...
! Package pdftex.def Error: File `media-types.png' not found.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.517 \includegraphics{media-types.png}

pandoc: Error producing PDF from TeX source
Makefile:30: recipe for target 'output/docs.pdf' failed
```

**Comment by vbatts** [comment]
Otherwise, https://github.com/opencontainers/image-spec/releases/tag/v0.1.0 from a :airplane:

**Comment by philips** [comment]
@vbatts Hrm, that is weird. Can you convert it to a jpg?

I am closing this out and will add the couple of additional issues as milestones to v0.2.0.

**Comment by vbatts** [comment]
I'll try a couple things
